/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiWorkforceRouteImport } from './routes/ai-workforce'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as HumanApprovalsRouteImport } from './routes/human-approvals'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkforceRoute = AiWorkforceRouteImport.update({
  id: '/ai-workforce',
  path: '/ai-workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanApprovalsRoute = HumanApprovalsRouteImport.update({
  id: '/human-approvals',
  path: '/human-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-workforce': typeof AiWorkforceRoute
  '/departments': typeof DepartmentsRoute
  '/human-approvals': typeof HumanApprovalsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-workforce': typeof AiWorkforceRoute
  '/departments': typeof DepartmentsRoute
  '/human-approvals': typeof HumanApprovalsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-workforce': typeof AiWorkforceRoute
  '/departments': typeof DepartmentsRoute
  '/human-approvals': typeof HumanApprovalsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ai-workforce' | '/departments' | '/human-approvals' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-workforce' | '/departments' | '/human-approvals' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ai-workforce'
    | '/departments'
    | '/human-approvals'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWorkforceRoute: typeof AiWorkforceRoute
  DepartmentsRoute: typeof DepartmentsRoute
  HumanApprovalsRoute: typeof HumanApprovalsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workforce': {
      id: '/ai-workforce'
      path: '/ai-workforce'
      fullPath: '/ai-workforce'
      preLoaderRoute: typeof AiWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-approvals': {
      id: '/human-approvals'
      path: '/human-approvals'
      fullPath: '/human-approvals'
      preLoaderRoute: typeof HumanApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWorkforceRoute: AiWorkforceRoute,
  DepartmentsRoute: DepartmentsRoute,
  HumanApprovalsRoute: HumanApprovalsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
